version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    version_requirement_updates: 'increase_versions'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all' # 開発中なのでdepsもauto-mergeする
    commit_message:
      prefix: 'chore(deps)'
