name: Benchmark test

on:
  push:
    branches:
      - master
      - improve-measure
  schedule:
    # JST で毎週土曜 12:00 (UTC で毎週土曜 3:00) に実行
    - cron: '0 3 * * SAT'

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        id: time
        run: echo "::set-output name=time::$(date +%s)"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install mkr command
        run: |
          curl -fsSL https://mackerel.io/file/script/setup-apt-v2.sh | sh
          sudo apt-get install mkr

      # playwright を github action 上で動かすのに必要
      - uses: microsoft/playwright-github-action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-yarn-

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      # yarn run benchmark:fps のためにサーバを立てておく
      - name: Start server
        run: yarn run webpack-cli serve --mode production &

      # NOTE: playwright を headful モードで起動しないと benchmark:memory が動かないので、xvfb-run を使い、playwright を headful モードで起動している
      # ref: https://github.com/microsoft/playwright-github-action#run-in-headful-mode
      - name: Run benchmark
        run: |
          yarn run --silent benchmark:fps | mkr throw --service rocketimer || true
          xvfb-run --auto-servernum -- yarn run --silent benchmark:memory | mkr throw --service rocketimer || true
        env:
          MACKEREL_APIKEY: ${{ secrets.MACKEREL_APIKEY }}
          TIME: ${{ steps.time.outputs.time }}
